package info.ilkinabdullayev.serializable.complex;

import java.io.Serializable;
import java.util.List;

public class Customer implements Serializable {

    //it can be generated by serialver command-app
    private static final long serialVersionUID = 2276411054808124647L;

    private int id;
    private String name;
    private int age;
    private List<Telephone> telephoneList;

    public Customer(int id, String name, int age, List<Telephone> telephoneList) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.telephoneList = telephoneList;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public List<Telephone> getTelephoneList() {
        return telephoneList;
    }

    public void setTelephoneList(List<Telephone> telephoneList) {
        this.telephoneList = telephoneList;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", telephoneList=" + telephoneList +
                '}';
    }
}
